Insertion sort
LevonKhazhoyan/hometasks-sem2 pull request #1
Opened 2022-06-10 07:49 UTC by LevonKhazhoyan

2022-08-01 11:40 UTC, yurii-litvinov requested changes

2022-08-01 11:40 UTC, yurii-litvinov commented on InsertionSortProj/InsertionSort/InsertionSort.cs
> +﻿namespace InsertionSortProj
В C# 10 появились file-scoped namespaces, теперь правильно писать `namespace InsertionSortProj;` и дальше без фигурной скобки и отступа.

2022-08-01 11:40 UTC, yurii-litvinov commented on InsertionSortProj/InsertionSort/InsertionSort.cs
> +    public class InsertionSort
Нужен комментарий в формате XML Documentation. Это не то чтобы всегда требуется в продакшене, но местное правило (потому что, вообще говоря, хороший тон). Надо комментарии к каждому классу и каждому его public-члену.

2022-08-01 11:40 UTC, yurii-litvinov commented on InsertionSortProj/InsertionSort/InsertionSort.cs
> +        private static void Main(string[] args)
А в C# 9 появились top-level statements, так что Main теперь в явном виде писать не нужно.

2022-08-01 11:40 UTC, yurii-litvinov commented on InsertionSortProj/InsertionSort/InsertionSort.cs
> +                var res = ConsoleArrayRead();
resolution? resistance? resources? Не сокращайте имена.

2022-08-01 11:40 UTC, yurii-litvinov commented on InsertionSortProj/InsertionSort/InsertionSort.cs
> +                Console.WriteLine("[{0}]", string.Join(", ", res));
```suggestion
                Console.WriteLine($"[{string.Join(", ", res)}]");
```

2022-08-01 11:40 UTC, yurii-litvinov commented on InsertionSortProj/InsertionSort/InsertionSort.cs
> +            catch (Exception ex)
Никогда не ловите исключения как просто Exception. В лекции про исключения дальше по курск даже рассказывается почему.

2022-08-01 11:40 UTC, yurii-litvinov commented on InsertionSortProj/InsertionSort/InsertionSort.cs
> +                    default:
Это как раз то, что должен делать catch

2022-08-01 11:40 UTC, yurii-litvinov commented on InsertionSortProj/InsertionSort/InsertionSort.cs
> +        public static void Sort(int[] arr)
![image](https://user-images.githubusercontent.com/706768/182139669-05cdcdde-496e-455b-a515-ab4fbe3e25fc.png)

Не сокращайте имена.

2022-08-01 11:40 UTC, yurii-litvinov commented on InsertionSortProj/InsertionSort/InsertionSort.cs
> +                        (arr[i], arr[i-1]) = (arr[i-1], arr[i]);
```suggestion
                        (arr[i], arr[i - 1]) = (arr[i - 1], arr[i]);
```
Бинарные операторы всегда отделяются пробелами.

2022-08-01 11:40 UTC, yurii-litvinov commented on InsertionSortProj/InsertionSort/InsertionSort.cs
> +            var numbers = Console.ReadLine().Split(' ');
CI огорчает тот факт, что ReadLine() может вернуть null, но тут на это не проверяется. Могло бы помочь так: 
```suggestion
            var numbers = Console.ReadLine()?.Split(' ');
```
Но тогда numbers надо было бы проверить на null. Но это нормально, код должен быть устойчив к ошибкам.

2022-08-01 11:40 UTC, yurii-litvinov commented on InsertionSortProj/InsertionSortTestProj/InsertionSortTests.cs
> +            Random rnd = new Random();
```suggestion
            var rnd = new Random();
```
Don't repeat yourself. И вообще, random должен быть полем, чтобы не создавать абсолютно одинаковые объекты для каждого теста. Сборщик мусора этому рад не будет.

2022-08-04 14:51 UTC, LevonKhazhoyan commented on InsertionSortProj/InsertionSort/InsertionSort.cs
> +﻿namespace InsertionSortProj
Справился с переходом на новую версию :)

2022-08-04 14:51 UTC, LevonKhazhoyan commented on InsertionSortProj/InsertionSort/InsertionSort.cs
> +    public class InsertionSort
Сделал

2022-08-04 14:52 UTC, LevonKhazhoyan commented on InsertionSortProj/InsertionSort/InsertionSort.cs
> +                var res = ConsoleArrayRead();
Больше не повторится.

2022-08-04 14:52 UTC, LevonKhazhoyan commented on InsertionSortProj/InsertionSort/InsertionSort.cs
> +                    default:
Не знаю под чем я это написал

2022-08-08 11:18 UTC, yurii-litvinov requested changes
Стало гораздо лучше, но можно ещё кое-что поправить

2022-08-08 11:18 UTC, yurii-litvinov commented on InsertionSortProj/InsertionSort/InsertionSort.cs
> +    public static int[] InsertionSort(int[] arr)
Нельзя параметры `arr` именовать, даже если это просто массив. `inputArray`, например, было бы лучше. И ниже тоже arr-ы встречаются, стоит исправить

2022-08-08 11:18 UTC, yurii-litvinov commented on InsertionSortProj/InsertionSort/InsertionSort.cs
> +        for (var sortedLen = 0; sortedLen < arr.Length; sortedLen++)
Тут тоже, не sortedLen, а sortedLength. Школьник-стайл какой-то :)

2022-08-08 11:18 UTC, yurii-litvinov commented on InsertionSortProj/InsertionSort/Program.cs
> +catch (FormatException e)
CI говорит, что просто `catch (FormatException)`, потому что с исключением Вы всё равно ничего не делаете, так что байндить его на переменную не нужно.

2022-08-08 11:18 UTC, yurii-litvinov commented on InsertionSortProj/InsertionSort/Program.cs
> +        var result = InsertionSortProj.InsertionSort(ConsoleArrayRead(input.Split(' ')));
Почему бы Split не делать в ConsoleArrayRead? Тогда бы было понятно разделение ответственности между функциями — одна координирует весь процесс, вторая парсит пользовательский ввод. А сейчас одна немного парсит и вторая парсит.

2022-08-08 11:18 UTC, yurii-litvinov commented on InsertionSortProj/InsertionSortTestProj/InsertionSortTests.cs
> +        var numbers = Enumerable.Range(1, _rnd.Next(1,400)).OrderBy(_ => _rnd.Next()).ToArray();
```suggestion
        var numbers = Enumerable.Range(1, _rnd.Next(1, 400)).OrderBy(_ => _rnd.Next()).ToArray();
```

2022-08-08 11:18 UTC, yurii-litvinov commented on InsertionSortProj/InsertionSortTestProj/InsertionSortTests.cs
> +    }
Пока так ок, но на будущее почитайте про https://docs.nunit.org/articles/nunit/writing-tests/attributes/testcase.html и https://docs.nunit.org/articles/nunit/writing-tests/attributes/testcasesource.html. Data-Driven-тесты умеет любой нормальный тестовый фреймворк, и если хочется один код потестить на разных данных, это правильный способ.

2022-08-28 18:05 UTC, yurii-litvinov approved these changes
Окей, зачтена. Стайлгайд ещё не очень, но для первой домашки сойдёт.

2022-08-28 18:05 UTC, yurii-litvinov commented on InsertionSortProj/InsertionSort/InsertionSort.cs
> +                {
```suggestion
                } 
                else
                {
```

2022-08-28 18:05 UTC, yurii-litvinov commented on InsertionSortProj/InsertionSortTestProj/InsertionSortTests.cs
> +    [TestCase(new [] { 6, 2, 9, 20, 130 }, TestName="PositiveNumbersSort" )]
```suggestion
    [TestCase(new [] { 6, 2, 9, 20, 130 }, TestName = "PositiveNumbersSort" )]
```
Это ж не Питон какой-то :)

2022-08-28 18:05 UTC, yurii-litvinov commented on InsertionSortProj/InsertionSortTestProj/InsertionSortTests.cs
> +        CompareInsertionSortWithSystemSort(bunchOfNumbers);
Теперь CompareInsertionSortWithSystemSort не нужен, можно его тело просто сюда перенести

2022-08-28 18:05 UTC, yurii-litvinov commented on InsertionSortProj/InsertionSortTestProj/InsertionSortTests.cs
> +    private int[] CreateIntArr()
"Создай целое, аррр!"

2022-10-03 15:42 UTC, merged